#!/bin/bash

export FILEPATH=$1
export LSTPATH=$2
export OUTBOX=$3
export FAA_ID=$4

# Extract HK sequences (based on names contained in .lst files) using seqtk subseq. Save in [MAG_ID]_temp.faa
seqtk subseq $FILEPATH $LSTPATH > ${FAA_ID}_temp.faa

# Rename extracted HK sequences according to [MAG_ID]-## (sequence order)
seqtk rename ${FAA_ID}_temp.faa $FAA_ID- > ${FAA_ID}_renamed.faa

# Concatenate all extracted HK sequences into one .faa file
cat ${FAA_ID}_renamed.faa >> allHKseq.faa

# Move extracted HK sequence files and temp files to outbox
mv ${FAA_ID}_renamed.faa $OUTBOX
mv ${FAA_ID}_temp.faa $OUTBOX
